name: Build SoftProjector

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:

    - name: Checkout repo at commit
      uses: actions/checkout@v4
      with:
        repository: SoftProjector/softprojector
        ref: 97a88e7295a92830ba70f34552c5a5f3a1043efd
        path: softprojector

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.5.3
        host: windows
        target: desktop
        arch: win64_msvc2019_64
        modules: qtmultimedia qt5compat

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: qmake
      shell: cmd
      working-directory: softprojector\src
      run: |
        qmake softProjector.pro CONFIG+=release

    - name: Build
      shell: cmd
      working-directory: softprojector\src
      run: |
        nmake

    - name: Deploy Qt
      shell: cmd
      working-directory: softprojector\src
      run: |
        windeployqt --release release\softProjector.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: softprojector-win64
        path: softprojector\src\release\*