name: Build SoftProjector Qt6

on:
  workflow_dispatch:
  push:
    branches: [ master, main ]

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      - name: Checkout exact commit
        uses: actions/checkout@v4
        with:
          repository: SoftProjector/softprojector
          ref: 97a88e7295a92830ba70f34552c5a5f3a1043efd

      - name: Install Qt 6
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.5.3
          host: windows
          target: desktop
          arch: win64_msvc2019_64
          modules: qtmultimedia qt5compat

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: qmake
        shell: cmd
        run: |
          qmake softProjector.pro CONFIG+=release

      - name: build
        shell: cmd
        run: |
          nmake

      - name: Deploy Qt runtime
        shell: cmd
        run: |
          windeployqt --release --qmldir . release\softProjector.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: softprojector-win64
          path: |
            release\*